# Generated by Django 3.0.5 on 2020-04-28 18:27

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(storage='/usr/src/app/static/search-image/', upload_to='')),
                ('image_data', jsonfield.fields.JSONField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
            ],
        ),
    ]
