# Generated by Django 3.0.5 on 2020-04-28 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_auto_20200428_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='procesed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_file',
            field=models.FileField(upload_to='searched-images/'),
        ),
    ]
