# Generated by Django 3.0.5 on 2020-04-28 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('base_url', models.TextField()),
                ('box_selector', models.TextField()),
                ('box_title_selector', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=40)),
                ('image_data', jsonfield.fields.JSONField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.CatalogProduct')),
            ],
        ),
    ]
